CREATE TABLE "instrument" (
	"id" uuid PRIMARY KEY DEFAULT pg_catalog.gen_random_uuid() NOT NULL,
	"symbol" text NOT NULL,
	"base_asset" text NOT NULL,
	"quote_asset" text DEFAULT 'USDT' NOT NULL,
	"contract_type" text DEFAULT 'PERPETUAL' NOT NULL,
	"status" text DEFAULT 'ACTIVE' NOT NULL,
	"tick_size" numeric(38, 18) NOT NULL,
	"min_price" numeric(38, 18) NOT NULL,
	"max_price" numeric(38, 18) NOT NULL,
	"step_size" numeric(38, 18) NOT NULL,
	"min_qty" numeric(38, 18) NOT NULL,
	"max_qty" numeric(38, 18) NOT NULL,
	"market_step_size" numeric(38, 18) NOT NULL,
	"market_min_qty" numeric(38, 18) NOT NULL,
	"market_max_qty" numeric(38, 18) NOT NULL,
	"min_notional" numeric(38, 18) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "instrument_symbol_unique" UNIQUE("symbol"),
	CONSTRAINT "instrument_symbol_uppercase" CHECK ("instrument"."symbol" = upper("instrument"."symbol")),
	CONSTRAINT "instrument_quote_asset_usdt" CHECK ("instrument"."quote_asset" = 'USDT'),
	CONSTRAINT "instrument_contract_type_perpetual" CHECK ("instrument"."contract_type" = 'PERPETUAL'),
	CONSTRAINT "instrument_status_valid" CHECK ("instrument"."status" in ('ACTIVE', 'INACTIVE')),
	CONSTRAINT "instrument_tick_size_non_negative" CHECK ("instrument"."tick_size" >= 0),
	CONSTRAINT "instrument_min_price_non_negative" CHECK ("instrument"."min_price" >= 0),
	CONSTRAINT "instrument_max_price_non_negative" CHECK ("instrument"."max_price" >= 0),
	CONSTRAINT "instrument_step_size_positive" CHECK ("instrument"."step_size" > 0),
	CONSTRAINT "instrument_min_qty_positive" CHECK ("instrument"."min_qty" > 0),
	CONSTRAINT "instrument_max_qty_positive" CHECK ("instrument"."max_qty" > 0),
	CONSTRAINT "instrument_qty_range" CHECK ("instrument"."max_qty" >= "instrument"."min_qty"),
	CONSTRAINT "instrument_market_step_size_positive" CHECK ("instrument"."market_step_size" > 0),
	CONSTRAINT "instrument_market_min_qty_positive" CHECK ("instrument"."market_min_qty" > 0),
	CONSTRAINT "instrument_market_max_qty_positive" CHECK ("instrument"."market_max_qty" > 0),
	CONSTRAINT "instrument_market_qty_range" CHECK ("instrument"."market_max_qty" >= "instrument"."market_min_qty"),
	CONSTRAINT "instrument_min_notional_positive" CHECK ("instrument"."min_notional" > 0)
);
