export const MARKET_BACKPRESSURE_BYTES = 1024 * 1024;
export const PRIVATE_BACKPRESSURE_BYTES = 256 * 1024;
export const MAX_MARKET_SUBSCRIPTIONS = 50;
export const MAX_INBOUND_PAYLOAD_BYTES = 4096;
export const MAX_PRIVATE_CONNECTIONS_PER_ACCOUNT = 4;
